BaseUrl= ""
LanguageCode= "en-GB"
Title= "Flaunting Flamingo Group"
paginate = 5
Copyright = ""
canonifyurls = true
theme="hugo-theme-air"

[author]
  name = "Flaunting Flamingo Group"

[permalinks]
    post = "/posts/:filename"

[params]
  description = "Lighting up your world with one computer at a time!"
  cover = "images/user.jpg"
  author = "The Flaunting Flamingo"
  authorlocation = ""
  bio= "my bio"
  logo = "images/user.png"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  mainSections = ["post"]
